CREATE OR REPLACE FUNCTION BARRY.GetDepartments()
RETURNS TABLE (
    DEPTNO    CHAR(3),
    DEPTNAME  VARCHAR(36),
    MGRNO     CHAR(6),
    ADMRDEPT  CHAR(3),
    LOCATION  CHAR(16)
)
BEGIN RETURN
SELECT
    DEPTNO,
    DEPTNAME,
    MGRNO,
    ADMRDEPT,
    LOCATION
FROM
    DEPARTMENT;
END;